doc/imv.1
I added the -n option, split the OPTIONS into FLAGS and OPTIONS as in the help message and did the same for the usage text.
There are still some inconsistencies however, for example **up** for zoom is listed in manpage but not in help, and **s** is mapped in code but written in neither.
=> add -n to manpage

doc/imv.1, src/main.c
Ok, I gave it a go and implemented the slideshow option. Should support all features you requested:
* `-t [time]` option to set how long to show each image for
* `t` key binding increases display time by 1 second
* `T` key binding decreases display time by 1 second
* If non-zero, the time left and display time should be shown in the overlay and window title in the form `[display-time-so-far/display-time]`
* A display time of `0` indicates the slideshow is not active
I wasn't sure how to force a redraw of the image (needed because window title and overlay have to be updated every second for the "countdown"). I don't think settings `view->redraw` directly is the best course of action.
Any suggestions/improvements/requests? Has been some time since I last touched a C codebase, so please …
=> Add slideshow option.

Makefile
Linking failed due to line 21 of the Makefile as $(LDFLAGS) was set immediately after $(CC).
[First pull request, hope I did this right...]
=> Fixed linking order to properly link libraries. Linking failed prior

src/main.c
At least on OpenBSD stdin, stdout and stderr are macros, and thus they are
expanded before compilation.
=> Don't use "stdin" variable name

doc/imv.1, src/main.c
"Monospace" is a font name reserved for default monospace font, which is
supposed to be set to particular font user prefers.
=> Use default font

Makefile, README.md
* Use `PREFIX` instead of `prefix` (compatibility with various package managers)
* Respect user's `CFLAGS`
* Avoid executing `sdl-config` multiple times
* More configuration options for install paths
* Verbose build mode
=> Build infrastructure improvements

Makefile
First and foremost: I forgot to change paths in uninstall. Next, I've moved tests and `imv` binary to `$(BUILDDIR)` and allowed setting the latter from environement. That allows using the same source tree by different hosts over NFS, or storing sources on read-only or slow medium. The last bit is using simply expanded variables, which allows make to carry less state around variables.
=> More changes to build infrastructure

Makefile
I introduced it to make object files depend on `$(BUILDDIR)` so that creating it could be moved into separate rule, executed once.  That was a bad idea, because `obj` had to be *phony*, thus making all targets that depend on it obsolete between runs of make.  This change introduces *order-only* rule that makes object files depend on `$(BUILDDIR)` without obsoleting other targets.
=> Drop `obj` target

Makefile, src/loader.c, src/main.c
As detected with `-Wmissing-prototypes`.
=> Hide functions that are not exposed via headers

README.md, doc/imv.1, src/loader.c, src/loader.h, src/main.c, src/navigator.c, src/util.c, src/util.h
This pull request is loosely based on #48, but it also changes processing of arguments:
* When called without arguments (with or without flags), imv reads list of files from standard input.
* When called with `-` among arguments, imv reads image data from standard input. Works for both still and animated images.
There is also a handful of more or less unrelated changes: small issues I've found and fixes while figuring out the proper way to get things done.
=> Loading image data from standard input

doc/imv.1, src/main.c
Although I've seen your recommendation in #77, I decided to present different approach.
* Add new switches: `-S` to force (default) "perfect fit" mode and `-s` to force "best fit" mode.
* Add new control key: `s` to switch scaling mode.
So far user don't really need to specify `-S` unless overrides default in some script. Thus scaling modes are basically controlled via switches `-a` (mnemonic: *a*ctual) and `-s` (mnemonic: *s*cale). In my opinion, it is easier to remember and less irritating to type then `-m best`.
Note, key `a` zooms to actual size without changing mode.
=> Add third scaling mode: best fit

README.md, src/main.c
This reduces delay before initial draw in case of slow input, opening possibilities for use cases like:
```shell
$ curl -Osw "%{filename_effective}\n" "http://www.example.com/[1-10].jpg" | imv
```
which will download all images and start showing them once first arrives.
Fixes #58, sort of.
=> Read file list from standard input continuosly

README.md, doc/imv.1, src/main.c, src/navigator.c, src/navigator.h
So I implemented the option dicussed in #84.
I chose `-x` for the switch (for eXit), because `-q` is commonly used to suppress output and `-o` is somewhat non-obvious.
I'm not really sure whether the change to the signature of `imv_navigator_select_rel()` is a good idea, but it looked like the easiest and cleanest way to do it this way for me.
All tests pass.
Closes #84
=> Add -x switch to exit imv when reaching end of file list.

src/main.c
Key handling code obuses the fact that plus sign is shifted key for equals sign
on US keyboard.  Add '+' as a control for layouts where this is not the case.
Fixes #88. @rumpelsepp, please test.
=> Make '+' work on all layouts

Makefile
When '--as-needed' linker flag is added to LDFLAGS, linker strips out
the symbols from the libraries needed for the tests due to the order
in which the libraries appear on the command line. List the source
files before the libraries to fix the linking issue.
For more information, see:
https://wiki.gentoo.org/wiki/Project:Quality_Assurance/As-needed#Importance_of_linking_order
Signed-off-by: Göktürk Yüksek <gokturk@gentoo.org>
=> Fix the linking order of tests in the Makefile for --as-needed

Makefile
Pretty printing gets in the way of debugging.  While "wall of text" build style may look intimidating, `imv` issues only a handful of build commands, so getting lost among them is difficult even on dumb terminal.  Provided that compiler warnings a coloured in newer compilers, I see no benefit in hiding compiler commands, not even as an option.
=> Unconditionally echo build commands

src/main.c
On certain platforms, like armv7h, [a char may be unsigned](http://stackoverflow.com/questions/2054939/is-char-signed-or-unsigned-by-default#2054941). The loop for getopt would loop forever because:
```
(char)-1 => 255 and 255 != -1
```
A signed char also worked. I don't know what that would mean for performance or portability. int feels simpler to me.
I'm using [Arch Linux ARM on the Samsung Chromebook 2](https://archlinuxarm.org/platforms/armv7/samsung/samsung-chromebook-2), which is armv7h. Not sure about other ARM platforms.
=> Store getopt() return in a signed variable

src/imv.c, src/viewport.c, src/viewport.h
With this change, if you scroll the image well beyond the viewport,
scrolling any amount in the other direction will immediately bring it
back on screen.
=> Prevent scrolling images indefinitely off-screen

AUTHORS, README.md, doc/imv.5.txt, src/binds.c, src/binds.h, src/commands.c, src/commands.h, src/imv.c, src/list.c
These commits address the feature request #130 for combining commands, because I really miss using <kbd>Shift</kbd>+<kbd>x</kbd> to both delete the current image and skip to the next one.
I thought the easiest way to do this would be to just change `bind_node.command` from a `char*` to a `struct list*` of `char*`s. That way, redefining a key bind does not overwrite the current one, but adds to the list. @eXeC64 I'd love to hear your opinion on this; though everything works on my end, maybe I overlooked something important while doing that change.
Also I noticed and fixed several memory leaks while checking the code.
=> Multiple commands per bind

src/navigator.c
`strndup` absence (line 64) breaks `test_navigator_add_remove`.
=> Expand relative paths (fixes #149)

Makefile
This will help with packaging things to meet current policies on
FreeBSD without having to patch things or manually strip binaries,
etc.
-D in FreeBSD's install(1) does not work like GNU install's -D and
is something else entirely.  Manually create the target directories
with mkdir first before installing files.
Note that the macro names are like that mostly for convenience
because it is already passed to builds by OpenBSD/FreeBSD ports.
=> Allow overriding install commands

Makefile
It could be a distinct action to INSTALL_PROGRAM which might be
overwritten to strip binaries.
=> Add INSTALL_SCRIPT to install scripts

doc/imv.1.txt, src/canvas.c, src/canvas.h, src/imv.c, src/viewport.c, src/viewport.h
Even though this was discussed in #92 I felt that solution was cumbersome and annoying if the image was not to be edited on disk. That approach would also be slow on large images.
These changes add commands for rotating by (arbitrary) angles and flipping horizontally and vertically. The actual transforms are just viewport transforms in the GL code.
The following commands are added:
```
rotate by <angle>
rotate to <angle>
flip horizontal
flip vertical
```
=> Add rotation and flipping commands

meson.build
Fix double-quoted version when building without git
Use pkg-config for libtiff dependency
Fixes #228
=> Fix double-quoted version when building without git

src/wl_window.c
1. Registry globals were not adequately waited for. A display roundtrip was added to fix this.
2. Content was commited irrespective of xdg_surface configure state. Track configure state and commit only after a configure is acked.
=> wayland: Protocol fixes

README.md
Realized I forgot to update the README when adding HEIF support.
=> Add libheif dependency to readme

README.md
The .gitignore file ignores the directory build/, therefore it makes
most sense to use this directory in the example as well.
=> README: Improve build instructions

src/wl_window.c
mmap with MAP_SHARED would fail if the compositor provides a read-only
descriptor with keymap. And at least weston applies F_SEAL_WRITE to the
memfd if supported by the platform.
Fixes #263
***
See also: https://gitlab.freedesktop.org/wayland/wayland/-/commit/905c0a341ddf0a885811d19e2b79c65a3f1d210c
On a side note, I believe I read somewhere that the keymap fd from wayland compositor is not guaranteed to be NULL-terminated.
If that's the case, `xkb_keymap_new_from_buffer` would be a safer choice.
=> Use private mapping for memfd with keymap.

src/navigator.c
Hello. The way directories are sorted bothers me, so I changed it to sort the images alphabetically. The way it's implemented avoids bloat and complicating the codebase - it's a very minor edit.
I understand that users have always been able to sort directories however they like, by using `stdin` as described in #146. I just feel that the current default behaviour isn't ideal.
I've tried to stick to `imv`'s coding style, so hopefully there aren't any problems there.
As for licensing, I'm no lawyer, but I'm not sure a change so minor can be copyrighted in the first place. If that isn't the case, though, then I agree to place my code under the MIT licence.
=> Sort directory entries alphabetically

.builds/freebsd.yml
the library is rewritten in rust and on freebsd there is an other
package for it.
=> FreeBSD: use librsvg2-rust instead of librsvg2

src/imv.c
Add newline to the prompt for reading paths from stdin.
Since string formatting isn't being used, it's possible to use fputs()
directly in the logging callback in imv.c.
=> imv: fix stdin prompt and use fputs.

src/imv.c, src/ipc.c
Since this isn't essential functionality, it's ok to simply not provide
it. In cases where XDG_RUNTIME_DIR was empty (but not unset) or set to a
directory where the user didn't have write permissions, socket creation
would fail and lead to segmentation faults in imv, due to the return
value of imv_ipc_create() not being checked.
=> imv, ipc: improve error checking for ipc creation. (CI failing because it can't find ubuntu image)

src/wl_window.c
https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/master/stable/xdg-shell/xdg-shell.xml#L1037
states regarding xdg_toplevel.configure "The width and height arguments specify a hint to the window". imv
was using these dimensions even if they are 0x0, which is valid for the compositor to send. Clearly this is
a bad hint and should be ignored. This patch does that, and fixes #293.
=> wayland: Fix initial black screen due to size of 0x0

doc/imv.1.txt, files/imv_config
This is the same key binding used by Eye of Gnome for a 90 degree clockwise image rotation for people coming from that image viewer.
This builds on the unreleased image rotatation and flipping feature, https://github.com/eXeC64/imv/pull/233
=> Add default keybinding for image rotation

src/viewport.c
Zooming on an exponential scale gives the user the perception of a constant zoom speed. This is because the user expects the size of the image to double with the same distance of scrolling, independently of the current zoom stage.
Note that I've only tested this on sway (wayland), aka works on my machine (TM). In addition to that, I've made sure that it still passes the cmocka tests. It would be nice if someone could check if this works as expected on X11.
=> Use exponential increments for zooming, fixes #239

meson.build
This allows for imv to work on a system where libX11 is fully removed
=> link against libOpenGL.so instead of (X11) libGL.so

src/navigator.c
All items' pathes are resolved in add_item() in the same file so path used in imv_navigator_find_path() should be resolved too.
This patch fixes #308
=> Resolve path in imv_navigator_find_path()

src/backend_libjpeg.c
There is a double-free issue in in `imv_free()` when a JPEG image is read from stdin:
```
$ imv - < ~/test.jpeg
double free or corruption (!prev)
[1]    73047 abort (core dumped)  imv - < ~/test.jpeg
```
The issue exists because the `open_memory()` function of the libjpeg backend stores a reference to `stdin_image_data` in `imv->current_source->private->data`. This heap-allocated memory is both free'd in `imv_free()` via `imv_source_free(imv->current_source);` and `free(imv->stdin_image_data);`.
This issue was fixed here by freeing this memory in `free_private()` (which gets called via `imv_source_free()`) only if the image data was actually read from a file (`private->fd >= 0`) and not via stdin.
=> fix double-free when backend libjpeg is used

src/navigator.c
Check `errno` when stat fail during traversal of a directory: doesn't stop
traversing for all stat errors
Should fix #335
=> Don't stop listing files in dir when stat fail

src/viewport.c
This fixes the zoom speed issue I mentioned in #336. The value of `1.04` was chosen to match the initial zoom speed when increments weren't exponential.
=> Fix zoom speed dependence on buffer/image width

src/canvas.c, src/canvas.h, src/imv.c, src/window.h, src/wl_window.c, src/x11_window.c
This fixes #319.
The changes I made are quite small and follow the existing code practice. The new code seems to work flawlessly on my Wayland (haven't tested in a multi-screen setup): now all the interface fonts are in the right places and have the right size.
But please review it nevertheless, this is my first time working with Cairo and Wayland!
See the commit message for details.
=> Scale fonts when Wayland updates scaling factor

src/x11_window.c
When a window is closed (for example, in i3 with Mod+Shift+Q) a destroy event is sent. imv with x11 currently has no handler for this event, therefore the event loop is never terminated and the program never stops. This pull request makes imv handle this event.
=> Fix lack of X11 window deletion event handling

src/canvas.c
The correct header to include is `cairo.h`, not `cairo/cairo.h`.
See https://gitlab.freedesktop.org/cairo/cairo/-/blob/master/doc/tutorial/src/include/cairo-tutorial.h.
That being said, this issue is quite common, see https://github.com/swaywm/sway/pull/6262.
Thank you.
=> cairo: Replace <cairo/cairo.h> by <cairo.h>
